title: Neha Ramachandar
#logo: <img src="https://github.com/neharamachandar/neharamachandar.github.io/assets/165216259/457022aa-b9f5-48f9-a705-f138d1720d02" alt="Logo" class="circle-image">
#description: Aspiring Business Analyst - Portfolio
show_downloads: true
theme: jekyll-theme-minimal
