title: Neha Ramachandar
#logo: <img src="https://github.com/neharamachandar/neharamachandar.github.io/assets/165216259/d689c74e-f2fa-4d7e-95ea-6a0f04d76032>
#description: Aspiring Business Analyst - Portfolio
show_downloads: true
theme: jekyll-theme-minimal
