title: Neha Ramachandar
#logo: https://github.com/neharamachandar/neharamachandar.github.io/blob/f9c77b4a30d0b7044b7420fd3f762c93a728f7d8/images/1696482362269.jpeg
#description: Aspiring Business Analyst - Portfolio
show_downloads: true
theme: jekyll-theme-minimal
